version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: my-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo-data:/data/db
      - ./docker-init:/docker-entrypoint-initdb.d

volumes:
  mongo-data:
